import numpy as np
matrix1=np.array([[1,2],[3,4]])
matrix2=np.array([[5,6],[7,8]])
print(matrix1)
print(matrix2)
sum=np.add(matrix1,matrix2)
print("sum:",sum)
product=np.multiply(matrix1,matrix2)
print("product:",product)
subtract=np.subtract(matrix1,matrix2)
print("Subtract:",subtract)
transpose=np.transpose(matrix1)
print("transpose:",transpose)